services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /app
    networks:
      - app-network
    container_name: frontend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
      - "10000:10000"
    env_file:
      - ./backend/.env
    command: go run main.go
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
    networks:
      - app-network
    container_name: backend

networks:
  app-network:
    driver: bridge